name: Reset Develop to Main

on:
  push:
    branches:
      - main

jobs:
  reset_develop_to_main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main

      - name: Configure Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Reset develop to main
        run: |
          git fetch origin main:main
          git fetch origin develop:develop
          git checkout develop
          git reset --hard main
          git push --force origin develop
